apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: fib-go
  namespace: user1-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/jduimovich0/fib-go@sha256:d7118edf6982fa7eb279092bb1e905900eb07ff704522c47c896700a47c83454
        name: container-image
        resources: {}
status: {}
