apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: haproxy
  namespace: user1-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/jduimovich0/haproxy@sha256:8c5176fd217e817503d66b93734d22df86b8363df080201b0a42d99e40278a12
        name: container-image
        resources: {}
status: {}
